version: '3.3'
services:
  semantle-tr:
    container_name: semantle-tr
    build: .
    networks:
      - web_nw
  nginx:
    container_name: semantle-tr-nginx
    image: "nginx:1.13.5"
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - semantle-tr
networks:
  web_nw:
    driver: bridge